#!/bin/sh

qemu-system-riscv64  -machine virt \
                     -smp 4 \
                     -m 4G \
                     -nographic \
                     -bios none \
                     -kernel $1
